// Generated by CoffeeScript 1.10.0
(function() {
  var hello, i, len, name, names;

  names = ["tanaka", "sasaki", "sato"];

  hello = function(name) {
    return alert("Hi, " + name);
  };

  for (i = 0, len = names.length; i < len; i++) {
    name = names[i];
    if (name.length > 5) {
      hello(name);
    }
  }

}).call(this);
