# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36c2bc8abb76fb27fc193731cbe0888bfa305cf387fc1d8f2eb97517745211ea5088323f63ad4533030af857ecf724007999587e61a1f00307e124cf0b36c7e6

test:
  secret_key_base: 67f9d6557e747c41ceda848ee0c098df769cdb0622d96982c3808449b9357be8c0a1d2ce93a3d8d3ed2ae8161ef6ac44326a28672f175d04e30edc78416430df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
